
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace IoTHub.Feature.Demo.Models
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
      
  /// <summary>Represents the "_Product Entry" template.</summary>
  public partial class __ProductEntry : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{F481CD06-BC8E-4DF7-A6C1-9CE08F65C5CA}");

    public __ProductEntry(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID ProductName = ID.Parse("{1DB00D6B-E441-4147-B903-1D25ED9818E8}");

      public static readonly ID Image = ID.Parse("{4EE7F2CB-C112-46FA-8419-63F77706BC16}");

      public static readonly ID Description = ID.Parse("{46FEA775-9D89-49BB-B1B1-16A61C7E9791}");

      public static readonly ID Features = ID.Parse("{469736EF-1582-4427-9865-70AB1074F046}");

    }
    
    /// <summary>Gets or sets the "Product Name" field.</summary>
    public string ProductName 
    {
      get 
      {
        return this.InnerItem[FieldIds.ProductName];
      }
      set
      {
        this.InnerItem[FieldIds.ProductName] = value;
      }
    }
  
    /// <summary>Gets the "Image" field.</summary>
    public ImageField Image 
    {
      get 
      {
        return this.InnerItem.Fields[FieldIds.Image];
      }
    }
  
    /// <summary>Gets or sets the "Description" field.</summary>
    public string Description 
    {
      get 
      {
        return this.InnerItem[FieldIds.Description];
      }
      set
      {
        this.InnerItem[FieldIds.Description] = value;
      }
    }
  
    /// <summary>Gets or sets the "Features" field.</summary>
    public string Features 
    {
      get 
      {
        return this.InnerItem[FieldIds.Features];
      }
      set
      {
        this.InnerItem[FieldIds.Features] = value;
      }
    }
  
    public static __ProductEntry Create(Item item) 
    {
      return new __ProductEntry(item);
    }

    public static implicit operator Item (__ProductEntry item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator __ProductEntry(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
